### ISSUE TITLE
Serialize event in separate column

### ISSUE THREAD

**Issue by patriknw** [SwissBorg/akka-persistence-postgres#91]
I think you serialize the full PersistentRepr?
I would highly recommend to serialize the event payload in a separate column and the other meta data from PersistentRepr in separate columns. That gives better ways to inspect the user data since it's not wrapped.

This is a flaw in akka-persistence-jdbc that we intend to change, see https://github.com/akka/akka-persistence-jdbc/issues/318

**Comment by mkubala** [comment]
Thanks for pointing this out!

Indeed having the meta data available directly on the DB level might make life easier. 
Given that you already have to perform old journal migration when start using the plugin this might be a perfect moment to introduce such a change.

**Comment by mkubala** [comment]
[The suggested solution](https://github.com/akka/akka-persistence-jdbc/issues/315) assumes that we will keep each meta data in a separate column.

This is probably the most generic solution, easy to implement on various different RDBMSes, although in terms of further migrations (if further version of Akka-persistence introduces additional meta information, we will have to add yet another column) we decided to leverage another PostgreSQL feature here - [support for JSONB column type](https://www.postgresql.org/docs/11/datatype-json.html).

I'm going to add only one additional column which will contains all the metadata and (thanks to [the built-in DB functions](https://www.postgresql.org/docs/11/functions-json.html)) still will be accessible at the DB level.
